### ISSUE TITLE
500 Internal Server Error on /search api

### ISSUE THREAD

**Issue by samyogdhital** [loorisr/crawlrouter#2]
I am seeing this bunch of logs on crawlrouter. And I think thus this is not working with deep-research agent we talked about previously.

```docker
Searching Donald Trump business dealings controversies with searxng on http://host.docker.internal:8080
Searching Donald Trump political campaigns analysis with searxng on http://host.docker.internal:8080
INFO:     172.22.0.1:43584 - "POST /v1/search HTTP/1.1" 500 Internal Server Error
INFO:     172.22.0.1:43582 - "POST /v1/search HTTP/1.1" 500 Internal Server Error
Searching Donald Trump legal challenges current status with searxng on http://host.docker.internal:8080
Searching Donald Trump media influence impact with searxng on http://host.docker.internal:8080
INFO:     172.22.0.1:43584 - "POST /v1/search HTTP/1.1" 500 Internal Server Error
INFO:     172.22.0.1:43582 - "POST /v1/search HTTP/1.1" 500 Internal Server Error

```

My crawlrouter code is just this

```docker
  crawlrouter:
    container_name: crawlrouter
    build: https://github.com/loorisr/crawlrouter.git
    ports:
      - "8000:8000"
    environment:
      - SCRAPE_BACKEND=firecrawl
      - SEARCH_BACKEND=searxng
      - FIRECRAWL_SCRAPE_ENDPOINT=http://host.docker.internal:3002/v1/scrape
      - FIRECRAWL_API_KEY=""
      - SEARXNG_ENDPOINT=http://host.docker.internal:8080
      - FIRECRAWL_TIMEOUT=30
      - CRAWL4AI_TIMEOUT=30
      - HTTP_TIMEOUT=30
    security_opt:
      - no-new-privileges=true
    read_only: true
    restart: unless-stopped
```

Have you noticed this problem? And do you think this is probelm with crawlrouter or searxng?

I can give you logs for searxng as well.
```
searxng             | [pid: 18|app: -1|req: -1/8] 172.19.0.1 () {30 vars in 564 bytes} [Sun Feb 16 19:18:12 2025] GET /search?q=Donald+Trump+business+dealings+controversies&format=json => generated 21 bytes in 0 msecs (HTTP/1.1 500) 3 headers in 102 bytes (0 switches on core 2)
searxng             | --- no python application found, check your startup logs for errors ---
searxng             | [pid: 18|app: -1|req: -1/9] 172.19.0.1 () {30 vars in 558 bytes} [Sun Feb 16 19:18:12 2025] GET /search?q=Donald+Trump+political+campaigns+analysis&format=json => generated 21 bytes in 0 msecs (HTTP/1.1 500) 3 headers in 102 bytes (0 switches on core 3)
searxng             | --- no python application found, check your startup logs for errors ---
searxng             | [pid: 18|app: -1|req: -1/10] 172.19.0.1 () {30 vars in 564 bytes} [Sun Feb 16 19:18:12 2025] GET /search?q=Donald+Trump+legal+challenges+current+status&format=json => generated 21 bytes in 0 msecs (HTTP/1.1 500) 3 headers in 102 bytes (0 switches on core 0)
searxng             | --- no python application found, check your startup logs for errors ---
searxng             | [pid: 18|app: -1|req: -1/11] 172.19.0.1 () {30 vars in 546 bytes} [Sun Feb 16 19:18:12 2025] GET /search?q=Donald+Trump+media+influence+impact&format=json => generated 21 bytes in 0 msecs (HTTP/1.1 500) 3 headers in 102 bytes (0 switches on core 1)
```

I think searxng is not generating error cuase the frontend is working perfectly and before you mention, I have -json mode turned on.

**Comment by samyogdhital** [comment]
I am running everything in a single docker compose file. I think this is not a problem. Cause it was working perviosuly but for some reason it is not working right now in that /search api.
But for cetain queries I see it is throwing 500 error.

Here is my full blown docker-compose file.
```
name: Deep-Research-Agent

x-common-service: &common-service
  build: firecrawl/apps/api
  ulimits:
    nofile:
      soft: 65535
      hard: 65535
  networks:
    - backend
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  playwright-service:
    container_name: playwright-service
    build: firecrawl/apps/playwright-service
    environment:
      - PORT=3000
      - PROXY_SERVER=${PROXY_SERVER}
      - PROXY_USERNAME=${PROXY_USERNAME}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
      - BLOCK_MEDIA=${BLOCK_MEDIA}
    networks:
      - backend

  api:
    <<: *common-service
    container_name: firecrawl-api
    environment:
      REDIS_URL: ${REDIS_URL:-redis://firecrawl-redis:6379}
      REDIS_RATE_LIMIT_URL: ${REDIS_URL:-redis://firecrawl-redis:6379}
      PLAYWRIGHT_MICROSERVICE_URL: ${PLAYWRIGHT_MICROSERVICE_URL:-http://playwright-service:3000}
      USE_DB_AUTHENTICATION: ${USE_DB_AUTHENTICATION}
      PORT: ${PORT:-3002}
      NUM_WORKERS_PER_QUEUE: ${NUM_WORKERS_PER_QUEUE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
      MODEL_NAME: ${MODEL_NAME:-gpt-4o}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
      LLAMAPARSE_API_KEY: ${LLAMAPARSE_API_KEY}
      LOGTAIL_KEY: ${LOGTAIL_KEY}
      BULL_AUTH_KEY: ${BULL_AUTH_KEY}
      TEST_API_KEY: ${TEST_API_KEY}
      POSTHOG_API_KEY: ${POSTHOG_API_KEY}
      POSTHOG_HOST: ${POSTHOG_HOST}
      SUPABASE_ANON_TOKEN: ${SUPABASE_ANON_TOKEN}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_TOKEN: ${SUPABASE_SERVICE_TOKEN}
      SCRAPING_BEE_API_KEY: ${SCRAPING_BEE_API_KEY}
      HOST: ${HOST:-0.0.0.0}
      SELF_HOSTED_WEBHOOK_URL: ${SELF_HOSTED_WEBHOOK_URL}
      SERPER_API_KEY: ${SERPER_API_KEY}
      SEARCHAPI_API_KEY: ${SEARCHAPI_API_KEY}
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      FLY_PROCESS_GROUP: app
    depends_on:
      - redis
      - playwright-service
    ports:
      - "3002:3002"
    command: [ "pnpm", "run", "start:production" ]

  worker:
    <<: *common-service
    container_name: firecrawl-worker
    environment:
      REDIS_URL: ${REDIS_URL:-redis://firecrawl-redis:6379}
      REDIS_RATE_LIMIT_URL: ${REDIS_URL:-redis://firecrawl-redis:6379}
      PLAYWRIGHT_MICROSERVICE_URL: ${PLAYWRIGHT_MICROSERVICE_URL:-http://playwright-service:3000}
      USE_DB_AUTHENTICATION: ${USE_DB_AUTHENTICATION}
      PORT: ${PORT:-3002}
      NUM_WORKERS_PER_QUEUE: ${NUM_WORKERS_PER_QUEUE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
      MODEL_NAME: ${MODEL_NAME:-gpt-4o}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
      LLAMAPARSE_API_KEY: ${LLAMAPARSE_API_KEY}
      LOGTAIL_KEY: ${LOGTAIL_KEY}
      BULL_AUTH_KEY: ${BULL_AUTH_KEY}
      TEST_API_KEY: ${TEST_API_KEY}
      POSTHOG_API_KEY: ${POSTHOG_API_KEY}
      POSTHOG_HOST: ${POSTHOG_HOST}
      SUPABASE_ANON_TOKEN: ${SUPABASE_ANON_TOKEN}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_TOKEN: ${SUPABASE_SERVICE_TOKEN}
      SCRAPING_BEE_API_KEY: ${SCRAPING_BEE_API_KEY}
      HOST: ${HOST:-0.0.0.0}
      SELF_HOSTED_WEBHOOK_URL: ${SELF_HOSTED_WEBHOOK_URL}
      LOGGING_LEVEL: ${LOGGING_LEVEL}
      FLY_PROCESS_GROUP: worker
    depends_on:
      - redis
      - playwright-service
      - api
    command: [ "pnpm", "run", "workers" ]

  redis:
    container_name: firecrawl-redis
    image: redis:alpine
    networks:
      - backend
    command: redis-server --bind 0.0.0.0


# --------------- Searxng
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - searxng
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    # cap_drop:
    #   - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  tor:
    container_name: tor
    image: dperson/torproxy:latest
    restart: unless-stopped
    networks:
      - searxng
    ports:
      - "9050:9050"
    # The default command exposes the SOCKS5 proxy on port 9050.
    command: -p 9050
    # cap_drop:
    #   - ALL
    extra_hosts:
    - "host.docker.internal:host-gateway"

# --------------- Crawlrouter
  crawlrouter:
    container_name: crawlrouter
    build: https://github.com/loorisr/crawlrouter.git
    ports:
      - "8000:8000"
    environment:
      - SCRAPE_BACKEND=firecrawl
      - SEARCH_BACKEND=searxng
      - FIRECRAWL_SCRAPE_ENDPOINT=http://host.docker.internal:3002/v1/scrape
      - FIRECRAWL_API_KEY=""
      - SEARXNG_ENDPOINT=http://host.docker.internal:8080
      - FIRECRAWL_TIMEOUT=30
      - CRAWL4AI_TIMEOUT=30
      - HTTP_TIMEOUT=30
    security_opt:
      - no-new-privileges=true
    read_only: true
    restart: unless-stopped

# --------------- Deep Research
  # deep-research:
  #   container_name: deep-research
  #   build: .
  #   env_file:
  #     - ./deep-research/.env.local
  #   tty: true
  #   stdin_open: true


networks:
  backend:
    driver: bridge
  searxng:
```

I am having a sinlge .env file with secrets of combined containers.

Here is what my folder structure look like.

![Image](https://github.com/user-attachments/assets/cd0c2736-e097-400d-94ac-e564c20b34d8)
